services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
                - utility
                - compute
              driver: nvidia
              count: all
    devices:
      - "/dev/nvidia0:/dev/nvidia0"
      - "/dev/nvidia1:/dev/nvidia1"
      - "/dev/nvidia2:/dev/nvidia2"
      - "/dev/nvidia3:/dev/nvidia3"
      - "/dev/nvidiactl:/dev/nvidiactl"
      - "/dev/nvidia-uvm:/dev/nvidia-uvm"
      - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    volumes:
      - .:/workspace:z
    ports:
      - "${JUPYTER_PORT}:9999"
    environment:
      - UID=${UID}
      - GID=${GID}
      - USER=${USER}
      - PYTHONPATH=/workspace
    command: |
      jupyter lab
        --ip=0.0.0.0
        --port=9999 
        --NotebookApp.use_redirect_file=False
        --no-browser
        --notebook-dir=/workspace/notebooks
        --NotebookApp.custom_display_url="http://localhost:${JUPYTER_PORT}"
